// =====================================================
// build.js — generates config.js from environment variables
//
// LOCAL:  reads your .env file, then run:  node build.js
// VERCEL: reads env vars from the Vercel dashboard automatically
// =====================================================

const fs = require('fs');

// If a .env file exists (local development), load it
if (fs.existsSync('.env')) {
  fs.readFileSync('.env', 'utf8')
    .split('\n')
    .forEach(line => {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) return; // skip blank lines and comments
      const [key, ...rest] = trimmed.split('=');
      if (key && !process.env[key.trim()]) {
        process.env[key.trim()] = rest.join('=').trim();
      }
    });
}

const url = process.env.SUPABASE_URL;
const key = process.env.SUPABASE_KEY;

if (!url || !key) {
  console.error('ERROR: SUPABASE_URL or SUPABASE_KEY is missing.');
  console.error('Local: make sure your .env file has both values.');
  console.error('Vercel: make sure both are added in the Vercel dashboard under Environment Variables.');
  process.exit(1);
}

fs.writeFileSync('config.js',
`// Auto-generated by build.js — do not edit this file directly.
// Edit .env (local) or Vercel environment variables (production) instead.
const SUPABASE_URL = '${url}';
const SUPABASE_KEY = '${key}';
`);

console.log('config.js generated successfully.');
